# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="invigorated_dimensions" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Invigorated Dimensions" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="invigorated_dimensions_logo.png" #optional
# A text field displayed in the mod UI
credits="Thanks to several older mods for not working for the idea to make this mod!" #optional
# A text field displayed in the mod UI
authors="BladeColdsteel" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Welcome to the Invigorated Dimensions Mod!

This mod is mostly intended to work within my modpack, Invigorated Monsters 2, a Pixelmon based modpack where all Pokemon spawn in different dimensions.

Sadly, some of the dimension mods I initially installed do not work with Pixelmon and it's BetterSpawnerConfig, so I decided to create this mod to replace those dimensions!

This mod is a complete overhaul where Pokemon spawn with Pixelmon installed. It adds multiple biomes and dimensions that are based off the typing of the Pokemon. You won't be able to find many types in the overworld now as it is mostly just normal type pokemon.
But if you're lucky, you can find the Elemental biomes related to each pokemon. Hoping to find a water-type? Try searching the Watery Rift! While the spawns are lower there, it does give you access to the Watery Depths! An all new dimension that has Water-Type Pokemon, and Spawns them in at higher rates!

There's a new biome and Dimension for each type to make Pokemon feel more rewarding when you find their biome/dimension!

(Not all dimensions/biomes are implemented, this is still a beta mod. They will be added as I go)
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.invigorated_dimensions]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.invigorated_dimensions]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invigorated_dimensions]]
    modId = "pixelmon"
    mandatory = true
    versionRange = "[9.1.11,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.invigorated_dimensions]]
    modId = "jei"
    mandatory = false
    versionRange = "[7.7.1.153,)"
    ordering = "AFTER"
    side = "BOTH"

